language: c

compiler:
    - clang
    - gcc

before_script:
    - sudo apt-get update -qq
    - sudo apt-get install libboost-all-dev
    - suto apt-get install libedit-dev

script:
    - ./bootstrap && ./configure --enable-tests && make && make check
